name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dartz: ^0.10.1
  dio: ^5.9.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  go_router: ^14.6.0
  mask_text_input_formatter: ^2.9.0
  country_picker: ^2.0.26
  google_maps_flutter: ^2.14.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  # Camera and Image
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  # OCR (Text Recognition)
  google_mlkit_text_recognition: ^0.11.0
  # Currency Conversion
  http: ^1.1.0
  intl: ^0.20.2
  # UI
  dropdown_search: ^5.0.6
  animated_bottom_navigation_bar: ^1.3.3
  shared_preferences: ^2.5.3
  provider: ^6.1.1
  flutter_gen: ^5.12.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  window_manager: ^0.5.1
  rxdart: ^0.28.0
  connectivity_plus: ^6.1.0
  flutter_dotenv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
